#!/usr/bin/env python3
"""Generate errata/README.md from the erratum files in errata/.

An erratum is one file, `errata/ATX-E-NNNN.md`, whose YAML frontmatter carries a
fixed set of keys (see FRONTMATTER_KEYS below) and whose body explains the
correction. The index at errata/README.md is a projection of those files and is
never edited by hand:

    python3 scripts/gen_errata_index.py            # rewrite errata/README.md
    python3 scripts/gen_errata_index.py --check    # exit 1 if it is stale

Running the generator twice yields a byte-identical file: the index is sorted by
erratum id, every value comes from the frontmatter, and nothing is stamped with a
build time. scripts/check_errata.py imports render_index() from here and fails
CI when the committed index differs from what the erratum files say.

The frontmatter parser also lives here, because the generator is the thing that
has to read every erratum: check_errata.py imports it rather than keeping a
second copy that could drift. It accepts the restricted YAML subset the erratum
template uses -- scalars, booleans, `- ` lists, `[]` flow lists and `|` block
scalars -- and rejects anything else, so an erratum cannot smuggle structure past
the validator. Every accepted document is also valid YAML.

Public text rule: nothing under errata/ names an implementation or its status,
because the errata say what the specification requires, not who passes. That rule is enforced by check_errata.py, which
holds the list; this generator copies only frontmatter values and erratum titles
into the index, so it cannot introduce one on its own.
"""

import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent

ERRATUM_STEM_RE = re.compile(r"^ATX-E-\d{4}$")
ERRATUM_ID_RE = re.compile(r"^ATX-E-\d{4}$")
ISO_DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")

# The frontmatter contract. A file carrying any other key, or missing one of
# these, is not an erratum.
FRONTMATTER_KEYS = (
    "id",
    "status",
    "class",
    "affectsDocument",
    "affectsWire",
    "sections",
    "oldText",
    "newText",
    "fixtures",
    "filed",
    "accepted",
)

STATUSES = ("proposed", "accepted", "incorporated")
CLASSES = ("editorial", "clarification", "security")

# Keys whose value is a list; every other key holds a scalar.
LIST_KEYS = ("sections", "fixtures")
# Keys whose value is a boolean.
BOOL_KEYS = ("affectsWire",)

GENERATED_BANNER = (
    "<!-- Generated by scripts/gen_errata_index.py from errata/ATX-E-*.md. "
    "Do not edit by hand. -->"
)


class FrontmatterError(Exception):
    """A frontmatter block that cannot be read, tagged with a rule name."""

    def __init__(self, rule, message):
        self.rule = rule
        self.message = message
        super().__init__(f"[{rule}] {message}")


def _scalar(raw):
    """One plain, quoted or boolean scalar value."""
    value = raw.strip()
    if value in ("true", "false"):
        return value == "true"
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
        return value[1:-1]
    return value


def _flow_list(raw):
    """`[]` or `[a, b, "c"]`."""
    inner = raw.strip()[1:-1].strip()
    if not inner:
        return []
    return [_scalar(item) for item in inner.split(",") if item.strip()]


def parse_frontmatter(text):
    """Read the leading `---` block of an erratum into a dict.

    Accepts the restricted YAML subset the template uses and rejects the rest,
    so that what the validator checks is exactly what a reader sees. Raises
    FrontmatterError, which carries the rule name the validator reports.
    """
    lines = text.split("\n")
    if not lines or lines[0].rstrip() != "---":
        raise FrontmatterError(
            "frontmatter-missing", "file does not open with a `---` frontmatter block"
        )
    try:
        end = next(i for i in range(1, len(lines)) if lines[i].rstrip() == "---")
    except StopIteration:
        raise FrontmatterError(
            "frontmatter-missing", "frontmatter block is never closed with `---`"
        )

    data = {}
    i = 1
    while i < end:
        line = lines[i]
        if "\t" in line:
            raise FrontmatterError(
                "frontmatter-syntax", f"line {i + 1} contains a tab; use spaces"
            )
        if not line.strip():
            i += 1
            continue
        m = re.match(r"^([A-Za-z][A-Za-z0-9_]*):(.*)$", line)
        if not m:
            raise FrontmatterError(
                "frontmatter-syntax",
                f"line {i + 1} is not `key: value`, `  - item` or a `|` block: {line!r}",
            )
        key, rest = m.group(1), m.group(2)
        if key in data:
            raise FrontmatterError("duplicate-key", f"key `{key}` appears twice")
        rest_stripped = rest.strip()
        i += 1

        if rest_stripped in ("|", "|-"):
            block = []
            indent = None
            while i < end:
                nxt = lines[i]
                if nxt.strip() and not nxt.startswith(" "):
                    break
                if nxt.strip() and indent is None:
                    indent = len(nxt) - len(nxt.lstrip(" "))
                block.append(nxt)
                i += 1
            while block and not block[-1].strip():
                block.pop()
            indent = indent or 0
            value = "\n".join(line[indent:] if line.strip() else "" for line in block)
            data[key] = value if rest_stripped == "|-" else (value + "\n" if value else "")
            continue

        if rest_stripped.startswith("[") and rest_stripped.endswith("]"):
            data[key] = _flow_list(rest_stripped)
            continue

        if rest_stripped == "":
            items = []
            while i < end and re.match(r"^\s+-\s", lines[i]):
                items.append(_scalar(re.sub(r"^\s+-\s", "", lines[i])))
                i += 1
            data[key] = items if items else ""
            continue

        data[key] = _scalar(rest_stripped)

    body = "\n".join(lines[end + 1 :]).lstrip("\n")
    return data, body


def erratum_paths(errata_dir):
    """Every erratum file in errata/, sorted by id. TEMPLATE.md is not one."""
    errata_dir = pathlib.Path(errata_dir)
    if not errata_dir.is_dir():
        return []
    return sorted(p for p in errata_dir.glob("*.md") if ERRATUM_STEM_RE.match(p.stem))


def title_of(body, erratum_id):
    """The erratum title: the body's first `# ` heading, minus its id prefix."""
    for line in body.split("\n"):
        if line.startswith("# "):
            heading = line[2:].strip()
            prefix = f"{erratum_id}:"
            if heading.startswith(prefix):
                heading = heading[len(prefix) :].strip()
            return heading
    return ""


def load_errata(errata_dir):
    """[(path, frontmatter, body, title)] for every erratum file, sorted by id."""
    loaded = []
    for path in erratum_paths(errata_dir):
        data, body = parse_frontmatter(path.read_text(encoding="utf-8"))
        loaded.append((path, data, body, title_of(body, data.get("id", path.stem))))
    return loaded


def incorporated_through(errata):
    """The highest `incorporated` erratum id, or "none"."""
    ids = sorted(
        str(data.get("id", ""))
        for _, data, _, _ in errata
        if data.get("status") == "incorporated"
    )
    return ids[-1] if ids else "none"


def _cell(value):
    """One table cell: pipes escaped, empty rendered as an em dash."""
    text = str(value).replace("|", "\\|").strip()
    return text if text else "—"


def render_index(errata_dir):
    """The full text of errata/README.md for the given errata directory."""
    errata = load_errata(errata_dir)
    out = [
        GENERATED_BANNER,
        "",
        "# ATX errata",
        "",
        "An erratum records a correction to published ATX specification text: what the",
        "text said, what it says instead, which sections move, whether the change reaches",
        "the wire format, and which conformance fixtures pin the corrected behaviour.",
        "Errata are how this document is corrected between releases; acceptance of an",
        "erratum is a document PATCH on the `MAJOR.MINOR.PATCH-{draft|rcN|final}` ladder.",
        "",
        "A correction to informative text that adds or removes no BCP 14 statement is a",
        "CHANGELOG.md entry, not an erratum. A BCP 14 statement is one that uses the key",
        "words listed in core.md's \"Conventions and terminology\" (MUST, SHOULD, MAY and",
        "the others).",
        "",
        "Each erratum is one file, `ATX-E-NNNN.md`, whose frontmatter carries `id`,",
        "`status`, `class`, `affectsDocument`, `affectsWire`, `sections`, `oldText`,",
        "`newText`, `fixtures`, `filed` and `accepted` — and no other key.",
        "",
        "**Status** is `proposed` (filed, not yet agreed), `accepted` (agreed, not yet",
        "folded into the document text) or `incorporated` (the document text now reads as",
        "the erratum says). **Class** is `editorial` (typography, formatting, references),",
        "`clarification` (the text was ambiguous; behaviour is unchanged) or `security`",
        "(the text as written permits an unsafe implementation).",
        "",
        "An erratum whose class is not `editorial` must add or change at least one",
        "conformance fixture before it can be accepted: the corrected behaviour has to be",
        "observable, not just written down. An accepted erratum must also appear in",
        "CHANGELOG.md.",
        "",
        "To file one, copy [TEMPLATE.md](TEMPLATE.md) to the next free `ATX-E-NNNN.md`,",
        "fill in the frontmatter, and regenerate this index:",
        "",
        "```",
        "python3 scripts/gen_errata_index.py",
        "```",
        "",
        "`scripts/check_errata.py` re-runs the generator in CI and fails if this file is",
        "stale, if a frontmatter key is wrong, or if an accepted erratum names no fixture.",
        "",
        f"**Incorporated through:** {incorporated_through(errata)}",
        "",
        "## Index",
        "",
    ]

    if not errata:
        out += ["No errata have been filed.", ""]
        return "\n".join(out)

    out += [
        "| Erratum | Title | Status | Class | Affects | Wire | Sections | Fixtures | Filed | Accepted |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for path, data, _, title in errata:
        erratum_id = str(data.get("id", path.stem))
        wire = "yes" if data.get("affectsWire") is True else "no"
        out.append(
            "| "
            + " | ".join(
                [
                    f"[{_cell(erratum_id)}]({path.name})",
                    _cell(title),
                    _cell(data.get("status", "")),
                    _cell(data.get("class", "")),
                    _cell(data.get("affectsDocument", "")),
                    wire,
                    _cell(", ".join(str(s) for s in data.get("sections") or [])),
                    _cell(", ".join(str(f) for f in data.get("fixtures") or [])),
                    _cell(data.get("filed", "")),
                    _cell(data.get("accepted", "")),
                ]
            )
            + " |"
        )
    out.append("")
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument(
        "--errata-dir",
        default=str(ROOT / "errata"),
        help="directory holding ATX-E-NNNN.md files (default: errata/)",
    )
    ap.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit 1 if the committed index is stale",
    )
    args = ap.parse_args()

    errata_dir = pathlib.Path(args.errata_dir)
    index_path = errata_dir / "README.md"
    try:
        wanted = render_index(errata_dir)
    except FrontmatterError as exc:
        print(f"errata frontmatter is unreadable: {exc}", file=sys.stderr)
        return 1

    if args.check:
        current = index_path.read_text(encoding="utf-8") if index_path.exists() else None
        if current == wanted:
            print(f"{index_path} is up to date")
            return 0
        print(
            f"{index_path} does not match the erratum files; "
            f"run python3 scripts/gen_errata_index.py",
            file=sys.stderr,
        )
        return 1

    with open(index_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(wanted)
    print(f"wrote {index_path} ({len(erratum_paths(errata_dir))} erratum file(s))")
    return 0


if __name__ == "__main__":
    sys.exit(main())
